version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: ai-test
      MINIO_ROOT_PASSWORD: Eme@123456
    command: server --console-address ":9001" /data
    restart: always
    networks:
      - app_network  # Attach minio to the custom network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - minio
    networks:
      - app_network  # Attach app to the custom network

networks:
  app_network:  # Define a custom network
    driver: bridge
